      - name: Install dependencies
        run: npm install
        working-directory: fisco

      - name: Run tests
        run: npm run coverage
        working-directory: fisco
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}

