name: Run Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./fisco
        run: npm install

      - name: Run tests
        working-directory: ./fisco
        run: npm run coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: ./fisco
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
