name: Run tests and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./fisco
        run: npm install
        

      - name: Run tests
        working-directory: ./fisco
        run: npm run coverage
          

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
  
      - name: Install Vercel CLI
        run: npm install -g vercel
  
      - name: Link Vercel Project
        working-directory: ./fisco
        run: vercel link --token=${{ secrets.VERCEL_TOKEN }} --yes
  
      - name: Pull Vercel Environment
        working-directory: ./fisco
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
  
      - name: Build Project
        working-directory: ./fisco
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
  
      - name: Deploy Project
        working-directory: ./fisco
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
